# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /post/:year/:month/:day/:title/

# Setup
title:            Max Claus Nunes
tagline:          Blog
description:      Software Developer
url:              http://maxcnunes.com

author:
  name:           Max Claus Nunes
  url:            https://twitter.com/maxcnunes

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/maxcnunes

comments:         true

gems: [jekyll-paginate, jekyll-gist]
