title = "Max Claus' website"
base_url = "https://maxclaus.xyz"
description = "Max Claus' personal website - About, Blog, Resume"

generate_feeds = true
feed_filenames = ["rss.xml"]

compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "css"

[link_checker]
skip_anchor_prefixes = [
    "https://github.com/",
]

[extra]
author = "Max Claus"
